spring.application.name=StatKick
football.api.base-url=https://api.football-data.org/v4
football.api.token=${FOOTBALL_API_TOKEN:}
statkick.cache.matches-ttl=20m

# ----------------------------------------
# Database Configuration (PostgreSQL)
# ----------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# JPA / Hibernate Configuration
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ----------------------------------------
# Flyway Migration
# ----------------------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ----------------------------------------
# Resilience4j - Circuit Breaker
# ----------------------------------------
resilience4j.circuitbreaker.instances.footballApi.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.footballApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.footballApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.footballApi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.footballApi.permitted-number-of-calls-in-half-open-state=3
# Only timeouts e Undisponibility (5xx)afect the circuit health
resilience4j.circuitbreaker.instances.footballApi.record-exceptions=dev.rangel.statkick.integration.footballapi.exception.ExternalTimeoutException,dev.rangel.statkick.integration.footballapi.exception.ExternalServiceUnavailableException

# ----------------------------------------
# Resilience4j - Rate Limiter
# ----------------------------------------
resilience4j.ratelimiter.instances.footballApi.limit-for-period=10
resilience4j.ratelimiter.instances.footballApi.limit-refresh-period=1m
resilience4j.ratelimiter.instances.footballApi.timeout-duration=0